# Generated by Django 5.2 on 2025-04-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('adoptada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adoptame.adoptante')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adoptame.mascota')),
            ],
        ),
    ]
