# Generated by Django 5.2 on 2025-04-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptame', '0004_adoptante_direccion_alter_adoptante_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='adoptante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptame.adoptante'),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptame.mascota'),
        ),
    ]
