# Generated by Django 5.2 on 2025-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='email',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='direccion',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
